
import re
 
CHAT_DICT = {
 
    # ─────────────────────────────────────────
    # NUMBERS AS WORDS / NUMERIC SLANG
    # ─────────────────────────────────────────
    "0": "zero",
    "1": "one",
    "2": "to",
    "3": "three",
    "4": "for",
    "5": "five",
    "6": "six",
    "7": "seven",
    "8": "ate",
    "9": "nine",
    "10": "ten",
    "10q": "thank you",
    "10x": "thanks",
    "2bad": "too bad",
    "2b": "to be",
    "2bh": "to be honest",
    "2day": "today",
    "2gether": "together",
    "2g2bt": "too good to be true",
    "2moro": "tomorrow",
    "2mrw": "tomorrow",
    "2nite": "tonight",
    "2u": "to you",
    "2u2": "to you too",
    "4ever": "forever",
    "4get": "forget",
    "4real": "for real",
    "4u": "for you",
    "4ward": "forward",
    "b4": "before",
    "b4n": "bye for now",
    "cu2": "see you too",
    "gr8": "great",
    "gr8t": "great",
    "h2g": "have to go",
    "j2lyk": "just to let you know",
    "j4f": "just for fun",
    "l8": "late",
    "l8r": "later",
    "l8ter": "later",
    "m8": "mate",
    "fr": "for real",
    "n2m": "not too much",
    "n2b": "not too bad",
    "r8": "rate",
    "sk8": "skate",
    "sk8r": "skater",
    "str8": "straight",
    "u2": "you too",
    "w8": "wait",
    "w8ing": "waiting",
    "x2": "times two",
    "g8": "great",
    "h8": "hate",
    "h8r": "hater",
    "s8n": "satan",
    "1ce": "once",
    "2ce": "twice",
    "3ce": "three times",
    "1st": "first",
    "2nd": "second",
    "3rd": "third",
    "4th": "fourth",
    "5th": "fifth",
    "cu18r": "see you later",
    "4col": "for crying out loud",
    "404": "not found or clueless",
    "411": "information",
    "911": "emergency",
    "101": "basics or introduction",
    "24/7": "all the time",
    "24seven": "all the time",
    "1337": "leet or elite hacker",
    "leet": "elite",
    "lol1": "laughing out loud",
    "rofl1": "rolling on the floor laughing",
    "msg": "message",
    "pic": "picture",
    "bro": "brother",
    "wtf": "what the hell",
    "asap": "as soon as possible",
    "lmao": "laughing hard",
    "imo": "in my opinion",

    # ─────────────────────────────────────────
    # GREETINGS & FAREWELLS
    # ─────────────────────────────────────────
    "gm": "good morning",
    "gn": "good night",
    "gd": "good",
    "hru": "how are you",
    "hyd": "how are you doing",
    "wyd": "what are you doing",
    "wbu": "what about you",
    "wb": "welcome back",
    "tc": "take care",
    "ttyl": "talk to you later",
    "ttys": "talk to you soon",
    "cya": "see you",
    "cu": "see you",
    "bye": "goodbye",
    "bbye": "bye bye",
    "sup": "what is up",
    "supp": "what is up",
    "wazzup": "what is up",
    "wassup": "what is up",
    "yo": "hello",
    "heya": "hello",
    "hiya": "hello",
    "howdy": "hello",
    "ello": "hello",
    "gday": "good day",
    "gdm": "good day mate",
    "morn": "good morning",
    "nite": "good night",
    "gnite": "good night",
    "g9": "good night",
    "gd9": "good night",
    "latur": "later",
    "ta": "thanks",
    "cheers": "thanks",
    "thks": "thanks",
    "thnx": "thanks",
    "thnks": "thanks",
    "tks": "thanks",
    "tyvm": "thank you very much",
    "tysm": "thank you so much",
    "tyty": "thank you thank you",
    "tnx": "thanks",
    "thx": "thanks",
    "tx": "thanks",
    "ty": "thank you",
    "tq": "thank you",
    "yw": "you are welcome",
    "np": "no problem",
    "nw": "no worries",
    "pls": "please",
    "plz": "please",
    "plox": "please",
    "sry": "sorry",
    "srry": "sorry",
    "soz": "sorry",
    "mb": "my bad",
    "mybad": "my bad",
    "holla": "hello or call me",
    "hollaa": "hello",
    "heyyy": "hey",
    "heyy": "hey",
    "heyyo": "hey",
    "whaddup": "what is up",
    "whattup": "what is up",
    "howzit": "how is it going",
    "howsit": "how is it going",
    "hows": "how is",
    "howd": "how did",
    "laters": "see you later",
    "later": "goodbye",
    "peace": "goodbye",
    "peace out": "goodbye",
    "deuces": "goodbye",
    "adios": "goodbye",
    "adieu": "farewell",
    "toodles": "goodbye",
    "tata": "goodbye",
    "chao": "goodbye",
    "ciao": "goodbye",
    "cheerio": "goodbye",
    "godspeed": "wishing you well",
    "godbye": "goodbye",
    "farewell": "goodbye",
    "aight": "alright",
    "ight": "alright",
    "aite": "alright",
    "gtg": "got to go",
    "g2g": "got to go",
    "g2b": "going to bed",
    "g2s": "going to sleep",
    "gotta": "got to",
    "brb": "be right back",
    "bbl": "be back later",
    "bbs": "be back soon",
    "bbiab": "be back in a bit",
    "bbiam": "be back in a minute",
    "bbiaf": "be back in a few",
    "brt": "be right there",
    "omw": "on my way",
    "otw": "on the way",
    "ilu":"i love you",

    # ─────────────────────────────────────────
    # COMMON ABBREVIATIONS & SHORTCUTS
    # ─────────────────────────────────────────
    "u": "you",
    "r": "are",
    "ur": "your",
    "y": "why",
    "k": "okay",
    "kk": "okay okay",
    "ok": "okay",
    "okk": "okay",
    "okok": "okay okay",
    "ya": "yes",
    "yep": "yes",
    "yup": "yes",
    "yups": "yes",
    "nope": "no",
    "nah": "no",
    "na": "no",
    "m": "am",
    "bc": "because",
    "bcz": "because",
    "bcoz": "because",
    "coz": "because",
    "cus": "because",
    "cuz": "because",
    "cos": "because",
    "b/c": "because",
    "w/": "with",
    "w/o": "without",
    "wt": "wait",
    "l8": "late",
    "2": "to",
    "4": "for",
    "n": "and",
    "nd": "and",
    "bt": "but",
    "jst": "just",
    "jus": "just",
    "juz": "just",
    "abt": "about",
    "alr": "already",
    "alrdy": "already",
    "rly": "really",
    "rlly": "really",
    "reli": "really",
    "vry": "very",
    "veri": "very",
    "v": "very",
    "dnt": "don't",
    "dont": "don't",
    "cant": "cannot",
    "wont": "will not",
    "isnt": "is not",
    "arent": "are not",
    "didnt": "did not",
    "doesnt": "does not",
    "havent": "have not",
    "wasnt": "was not",
    "wouldnt": "would not",
    "couldnt": "could not",
    "shouldnt": "should not",
    "i'm": "i am",
    "its": "it is",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "jk": "just kidding",
    "jkjk": "just kidding just kidding",
    "lmk": "let me know",
    "hmu": "hit me up",
    "smth": "something",
    "sth": "something",
    "nthing": "nothing",
    "nth": "nothing",
    "evrythng": "everything",
    "evry": "every",
    "evn": "even",
    "thru": "through",
    "tho": "though",
    "altho": "although",
    "cmon": "come on",
    "dat": "that",
    "dis": "this",
    "dese": "these",
    "dem": "them",
    "der": "there",
    "dere": "there",
    "ders": "there is",
    "wot": "what",
    "wots": "what is",
    "wats": "what is",
    "wat": "what",
    "hw": "how",
    "hws": "how is",
    "wen": "when",
    "wer": "where",
    "wit": "with",
    "gonna": "going to",
    "wanna": "want to",
    "kinda": "kind of",
    "sorta": "sort of",
    "hafta": "have to",
    "dunno": "don't know",
    "lemme": "let me",
    "gimme": "give me",
    "tryna": "trying to",
    "prolly": "probably",
    "probs": "probably",
    "prob": "probably",
    "def": "definitely",
    "deffo": "definitely",
    "defo": "definitely",
    "obv": "obviously",
    "obvs": "obviously",
    "abs": "absolutely",
    "tbqh": "to be quite honest",
    "ftw": "for the win",
    "fwiw": "for what it is worth",
    "tmi": "too much information",
    "tbf": "to be fair",
    "nbd": "no big deal",
    "nt": "no thanks",
    "nty": "no thank you",
    "alrighty": "alright",
    "mkay": "okay",
    "mhm": "yes",
    "mmk": "okay",
    "mmhm": "yes",
    "ahh": "i see",
    "ohh": "i see",
    "ohhh": "i see",
    "ahhhh": "i see",
    "oops": "i made a mistake",
    "whoops": "i made a mistake",
    "doh": "i made a mistake",
    "duh": "obviously",
    "doh": "of course",
    "pff": "i am not impressed",
    "pfft": "i am not impressed",
    "hmm": "i am thinking",
    "hm": "i am thinking",
    "hmph": "i am displeased",
    "hmp": "i am displeased",
    "eh": "i don't care or maybe",
    "meh": "i don't care",
    "bleh": "i feel bad",
    "ugh": "i am frustrated",
    "eww": "that is gross",
    "ew": "that is gross",
    "brr": "it is cold",
    "eek": "i am scared",
    "yikes": "that is bad or scary",
    "oof": "that is unfortunate",
    "rip": "rest in peace",
    "smfh": "shaking my freaking head",
    "smgdh": "shaking my god damn head",
    "ffs": "for goodness sake",
    "fml": "my life is frustrating",
    "ftl": "for the loss",
    "afaik": "as far as i know",
    "afaict": "as far as i can tell",
    "afaic": "as far as i am concerned",
    "iirc": "if i recall correctly",
    "iinm": "if i'm not mistaken",
    "iiuc": "if i understand correctly",
    "tia": "thanks in advance",
    "tyia": "thank you in advance",
    "np": "no problem",
    "nbd": "no big deal",
    "yw": "you are welcome",
    "de nada": "you are welcome",
    "no worries": "it is fine",
    "all good": "it is fine",
    "all gud": "it is fine",
    "s'all good": "it is all good",
    "nw": "no worries",
    "noworries": "no worries",

    # ─────────────────────────────────────────
    # EMOTIONS & REACTIONS
    # ─────────────────────────────────────────
    "lol": "laughing out loud",
    "lmao": "laughing my head off",
    "lmfao": "laughing my freaking head off",
    "rofl": "rolling on the floor laughing",
    "roflmao": "rolling on the floor laughing my head off",
    "roflcopter": "rolling on the floor laughing",
    "haha": "laughing",
    "hehe": "laughing softly",
    "hihi": "laughing cutely",
    "heehee": "giggling",
    "omg": "oh my goodness",
    "omfg": "oh my freaking goodness",
    "omw": "oh my word",
    "wtf": "what the heck",
    "wth": "what the heck",
    "wtaf": "what the actual heck",
    "idgaf": "i do not care at all",
    "smh": "shaking my head",
    "fml": "my life is so frustrating",
    "ikr": "i know right",
    "ik": "i know",
    "ngl": "not gonna lie",
    "tbh": "to be honest",
    "ily": "i love you",
    "ily2": "i love you too",
    "ilysm": "i love you so much",
    "ilysmm": "i love you so so much",
    "luv": "love",
    "lylas": "love you like a sister",
    "lylab": "love you like a brother",
    "xoxo": "hugs and kisses",
    "xo": "hugs and kisses",
    "aww": "that is sweet",
    "awww": "that is sweet",
    "awwww": "that is really sweet",
    "yay": "hooray",
    "woah": "wow",
    "woww": "wow",
    "wowww": "wow",
    "woow": "wow",
    "omgg": "oh my goodness",
    "omgggg": "oh my goodness",
    "lolol": "laughing so much",
    "lololol": "laughing so much",
    "lmaoo": "laughing so hard",
    "lmaooo": "laughing really hard",
    "hahaha": "laughing a lot",
    "hahahaha": "laughing a lot",
    "lulz": "laughing out loud",
    "lawl": "laughing out loud",
    "kek": "laughing",
    "kekw": "laughing hard",
    "lul": "laughing",
    "luls": "laughing",
    "xd": "laughing face",
    "xdd": "laughing a lot",
    "xddd": "laughing really hard",
    "uwu": "cute affectionate expression",
    "owo": "surprised cute expression",
    "owo": "surprised cute expression",
    "o.o": "surprised expression",
    "o_o": "surprised expression",
    "o.O": "confused surprised expression",
    "T_T": "crying expression",
    "TT": "crying",
    "TwT": "crying cute expression",
    "QwQ": "crying cute expression",
    "OwO": "surprised expression",
    "UwU": "cute loving expression",
    ":)": "smiling",
    ":-)": "smiling",
    ":D": "big smile",
    ":-D": "big smile",
    ":(": "sad face",
    ":-(": "sad face",
    ":P": "sticking tongue out",
    ":-P": "sticking tongue out",
    ";)": "winking",
    ";-)": "winking",
    ":O": "shocked",
    ":-O": "shocked",
    ":3": "cute face",
    "^_^": "happy face",
    "^.^": "happy face",
    "-_-": "unimpressed face",
    ">_<": "frustrated face",
    "<3": "heart or love",
    "</3": "broken heart",
    "B)": "cool face",
    "B-)": "cool face",
    "8)": "cool face with glasses",
    ">:)": "evil grin",
    "O:)": "angel face",
    ":')": "happy crying",
    ":'(": "sad crying",
    ":/": "unsure face",
    ":\\": "unsure face",
    ":s": "confused face",
    ":$": "embarrassed face",
    ":*": "kiss",
    ":-*": "kiss",
    "XD": "laughing hard",
    "X)": "laughing hard",
    "shocked": "very surprised",
    "triggered": "upset or angered",
    "salty": "bitter or upset",
    "shook": "shocked",
    "dead": "found extremely funny",
    "ded": "found extremely funny",
    "deceased": "found extremely funny",
    "crying": "laughing very hard",
    "screaming": "shocked or excited",
    "obsessed": "really like something",
    "living": "really enjoying",
    "hyped": "very excited",
    "hype": "excitement",
    "chillin": "relaxing",
    "chill": "relax",
    "vibing": "relaxing or enjoying",
    "depresso": "depressed",
    "sadge": "sad",
    "sadgee": "very sad",
    "pog": "play of the game or amazing",
    "poggers": "amazing or exciting",
    "pogchamp": "amazing play",
    "pepega": "foolish expression",
    "monkaS": "anxious scared expression",
    "pepehands": "sad expression",
    "pepelaugh": "laughing expression",
    "copium": "coping mechanism",
    "hopium": "false hope",
    "malding": "mad and balding or frustrated",

    # ─────────────────────────────────────────
    # AGREEMENT / DISAGREEMENT
    # ─────────────────────────────────────────
    "fasho": "for sure",
    "fosho": "for sure",
    "fersure": "for sure",
    "forsure": "for sure",
    "totes": "totally",
    "totez": "totally",
    "defs": "definitely",
    "absol": "absolutely",
    "absly": "absolutely",
    "nopee": "no",
    "naw": "no",
    "naww": "no",
    "yas": "yes",
    "yasss": "yes",
    "yass": "yes",
    "yaaaas": "yes",
    "hellyes": "absolutely yes",
    "truee": "true",
    "tru": "true",
    "truu": "true",
    "frfr": "for real for real",
    "frrr": "for real",
    "fr": "for real",
    "frreal": "for real",
    "nocap": "no lie",
    "no cap": "no lie",
    "ong": "on god i swear",
    "on god": "i swear",
    "word": "i agree",
    "wordd": "i agree",
    "say less": "understood i agree",
    "deadass": "seriously",
    "deadazz": "seriously",
    "srsly": "seriously",
    "srs": "serious",
    "istg": "i swear to god",
    "swear": "i swear",
    "s2g": "swear to god",
    "pinky": "i promise",
    "bet": "okay or agreed",
    "hard pass": "definitely no",
    "hard yes": "absolutely yes",
    "pass": "no thanks",
    "periodt": "end of discussion",
    "period": "end of discussion",
    "based": "admirable or agreeable",
    "cap": "lie",
    "capping": "lying",
    "sus": "suspicious",
    "suss": "suspicious",
    "valid": "acceptable or true",
    "invalid": "not acceptable",
    "facts": "that is true",
    "fax": "that is true",
    "true": "that is correct",
    "false": "that is wrong",
    "wrong": "that is incorrect",
    "correct": "that is right",
    "exactly": "precisely right",
    "precisely": "exactly right",
    "agreed": "i agree",
    "disagree": "i do not agree",
    "debatable": "arguable",
    "arguably": "it could be argued",
    "controversial": "widely debated",
    "contested": "widely disputed",

    # ─────────────────────────────────────────
    # ASKING & QUESTIONING
    # ─────────────────────────────────────────
    "wdym": "what do you mean",
    "wdyt": "what do you think",
    "wdyd": "what did you do",
    "wdys": "what did you say",
    "wdyg": "what do you got",
    "wuu2": "what are you up to",
    "wuup2": "what are you up to",
    "u up": "are you awake",
    "u ok": "are you okay",
    "hbu": "how about you",
    "hby": "how about you",
    "howbou": "how about",
    "howbow": "how about",
    "wdw": "what do you want",
    "wut": "what",
    "wah": "what",
    "whaaat": "what",
    "whoa": "wow or what",
    "huh": "what or i do not understand",
    "eh": "what or i do not understand",
    "hmm": "i am thinking",
    "uh": "hesitation",
    "uhh": "hesitation",
    "uhhh": "hesitation",
    "umm": "hesitation",
    "ummm": "hesitation",
    "sooo": "so",
    "soooo": "so",
    "welp": "well",
    "welll": "well",
    "oof": "oh no",
    "ooff": "oh no",
    "rly": "really",
    "rn": "right now",
    "jsyk": "just so you know",
    "jfyi": "just for your information",
    "jic": "just in case",
    "wip": "work in progress",
    "eta": "estimated time of arrival",
    "otp": "on the phone or one true pair",

    # ─────────────────────────────────────────
    # TEXTING SHORTCUTS
    # ─────────────────────────────────────────
    "idk": "i do not know",
    "idc": "i do not care",
    "idgaf": "i do not care at all",
    "idfk": "i have no idea",
    "nvm": "never mind",
    "nm": "never mind",
    "nvmd": "never mind",
    "afk": "away from keyboard",
    "irl": "in real life",
    "atm": "at the moment",
    "asap": "as soon as possible",
    "fyi": "for your information",
    "tbf": "to be fair",
    "imo": "in my opinion",
    "nbd": "no big deal",
    "nt": "no thanks",
    "otp": "on the phone",
    "brt": "be right there",
    "rt": "right",
    "alr": "alright",
    "nm": "not much",
    "nmu": "not much you",
    "ntm": "not too much",
    "jsyk": "just so you know",
    "jfyi": "just for your information",
    "jic": "just in case",
    "wip": "work in progress",
    "eta": "estimated time of arrival",
    "lmao": "laughing my head off",
    "g2b": "going to bed",
    "g2s": "going to sleep",
    "brbs": "be right back soon",
    "msg": "message",
    "msgs": "messages",
    "txt": "text",
    "txtd": "texted",
    "txting": "texting",
    "dm": "direct message",
    "dms": "direct messages",
    "pm": "private message",
    "pms": "private messages",
    "vc": "voice chat",
    "gc": "group chat",
    "grp": "group",
    "convo": "conversation",
    "convos": "conversations",
    "chat": "conversation",
    "chats": "conversations",
    "lmk": "let me know",
    "hmu": "hit me up",
    "hml": "hit my line",
    "holla": "call or message me",
    "ring": "call me",
    "buzz": "call me",
    "ping": "message me",
    "drop": "send or share",
    "link": "connect or send a link",
    "linked": "connected or sent a link",
    "slide": "come over or message",
    "slide in": "message someone",
    "slid in": "messaged someone",
    "slid": "messaged",
    "replied": "responded",
    "repped": "represented",
    "left on read": "seen but not replied",
    "ghosted": "stopped replying suddenly",
    "ghosting": "ignoring someone",
    "ghost": "ignore someone",
    "left on seen": "seen but not replied",
    "seen": "read the message",
    "blue ticked": "seen but not replied",
    "read receipt": "seen confirmation",
    "double text": "send two messages in a row",
    "spam": "send many messages",
    "spamming": "sending many messages",

    # ─────────────────────────────────────────
    # SOCIAL MEDIA & INTERNET SLANG
    # ─────────────────────────────────────────
    "ootd": "outfit of the day",
    "tbt": "throwback thursday",
    "wcw": "woman crush wednesday",
    "mcm": "man crush monday",
    "fb": "facebook",
    "ig": "instagram",
    "yt": "youtube",
    "wp": "whatsapp",
    "tw": "twitter",
    "rt": "retweet",
    "ff": "follow friday",
    "ama": "ask me anything",
    "tfw": "that feeling when",
    "mfw": "my face when",
    "mrw": "my reaction when",
    "eli5": "explain like i am five",
    "til": "today i learned",
    "oc": "original content",
    "op": "original poster",
    "ftfy": "fixed that for you",
    "yolo": "you only live once",
    "fomo": "fear of missing out",
    "goat": "greatest of all time",
    "lit": "exciting or amazing",
    "fire": "amazing",
    "slay": "doing great",
    "vibe": "feeling or mood",
    "lowkey": "secretly or quietly",
    "highkey": "openly or very much",
    "bussin": "really good",
    "snatched": "looking amazing",
    "extra": "over the top",
    "shade": "disrespect",
    "tea": "gossip",
    "spill": "share gossip",
    "spill the tea": "share the gossip",
    "sis": "sister",
    "bro": "brother",
    "bruh": "expression of disbelief",
    "brah": "brother",
    "fam": "family or close friends",
    "squad": "close friend group",
    "crew": "close friend group",
    "bae": "loved one",
    "bff": "best friends forever",
    "bf": "boyfriend",
    "gf": "girlfriend",
    "bffl": "best friends for life",
    "bestie": "best friend",
    "main": "primary person or character",
    "main character": "acting like story is about you",
    "npc": "boring unoriginal person",
    "pick me": "attention seeker",
    "karen": "entitled complainer",
    "boomer": "old fashioned person",
    "zoomer": "generation z person",
    "millennial": "generation y person",
    "stan": "extreme fan",
    "fanboy": "extreme male fan",
    "fangirl": "extreme female fan",
    "hater": "someone who criticizes unfairly",
    "clout": "fame or influence",
    "clout chasing": "seeking fame",
    "flex": "show off",
    "humble": "not arrogant",
    "petty": "small minded",
    "messy": "drama causing",
    "basic": "mainstream or ordinary",
    "trash": "bad or poor quality",
    "cringe": "embarrassing",
    "cringy": "embarrassing",
    "mid": "average or mediocre",
    "overrated": "not as good as people say",
    "underrated": "better than people think",
    "slept on": "underappreciated",
    "woke": "socially aware",
    "cancel": "publicly boycott someone",
    "cancelled": "publicly boycotted",
    "cancel culture": "trend of boycotting people",
    "cancelled him": "publicly boycotted him",
    "ratio": "getting more replies than likes",
    "ratioed": "got more replies than likes",
    "L": "loss or failure",
    "W": "win or success",
    "take the L": "accept defeat",
    "take the W": "accept the win",
    "big L": "major failure",
    "big W": "major success",
    "dub": "win",
    "dubbing": "winning",
    "L ratio": "you lost and got ratioed",
    "the audacity": "how dare they",
    "the nerve": "how dare they",
    "retweet": "i agree share this",
    "share": "spread this",
    "viral": "widely spread online",
    "trending": "popular right now",
    "trend": "popular thing right now",
    "algorithm": "platform content system",
    "algo": "algorithm",
    "fyp": "for you page",
    "foryou": "for you page",
    "foryoupage": "for you page",
    "explore": "discovery page",
    "feed": "content timeline",
    "timeline": "content feed",
    "post": "upload or share content",
    "posted": "shared content",
    "story": "temporary social media post",
    "stories": "temporary social media posts",
    "reel": "short video",
    "reels": "short videos",
    "clip": "short video",
    "clips": "short videos",
    "shorts": "short youtube videos",
    "short": "short video",
    "content": "online material",
    "creator": "content maker",
    "influencer": "social media personality",
    "collab": "collaboration",
    "collabs": "collaborations",
    "sponsor": "paid promotion",
    "sponsored": "paid promotion",
    "ad": "advertisement",
    "promo": "promotion",
    "plug": "recommendation or promotion",
    "plugging": "promoting",
    "shoutout": "public mention",
    "sfs": "shoutout for shoutout",
    "f4f": "follow for follow",
    "l4l": "like for like",
    "spam4spam": "spam likes for spam likes",
    "tag": "mention someone",
    "tagged": "mentioned someone",
    "tagging": "mentioning someone",
    "mention": "reference to someone",
    "mentioned": "referenced someone",
    "hashtag": "keyword tag",
    "hash": "number sign",
    "verified": "confirmed authentic account",
    "blue tick": "verified status",
    "checkmark": "verified status",
    "follower": "subscriber",
    "followers": "subscribers",
    "following": "accounts you subscribe to",
    "mutuals": "people who follow each other",
    "mutual": "shared connection",
    "moots": "mutuals",
    "moot": "mutual",
    "lurk": "watch without interacting",
    "lurking": "watching without interacting",
    "lurker": "someone who watches without interacting",
    "scroll": "browse content",
    "scrolling": "browsing content",
    "doomscroll": "endlessly scroll bad news",
    "doomscrolling": "endlessly scrolling bad news",
    "chronically online": "spending too much time online",
    "touch grass": "go outside and get fresh air",
    "offline": "not connected",
    "online": "connected",
    "irl": "in real life",
    "afk": "away from keyboard",

    # ─────────────────────────────────────────
    # RELATIONSHIP & PERSONAL
    # ─────────────────────────────────────────
    "hubby": "husband",
    "wifey": "wife",
    "babe": "loved one",
    "bb": "baby",
    "bby": "baby",
    "babes": "baby",
    "hun": "honey",
    "huns": "honey",
    "hon": "honey",
    "luvya": "love you",
    "crush": "person you like romantically",
    "ex": "ex partner",
    "exes": "ex partners",
    "so": "significant other",
    "s/o": "significant other",
    "bfgf": "boyfriend girlfriend",
    "mia": "missing in action",
    "wifed": "married",
    "situationship": "undefined relationship",
    "talking": "casually dating",
    "talking stage": "early dating phase",
    "dating": "in a romantic relationship",
    "dating app": "app for finding partners",
    "match": "romantic connection",
    "matched": "connected romantically",
    "swipe right": "like someone on dating app",
    "swipe left": "dislike someone on dating app",
    "ghosted": "stopped replying suddenly",
    "ghosting": "ignoring someone suddenly",
    "ghost": "ignore someone",
    "benching": "keeping someone as backup",
    "benched": "kept as backup",
    "breadcrumbing": "giving minimal attention",
    "breadcrumbed": "given minimal attention",
    "love bombing": "overwhelming with affection",
    "love bombed": "overwhelmed with affection",
    "simping": "being overly devoted",
    "simp": "overly devoted person",
    "simped": "was overly devoted",
    "friendzone": "placed in friend category",
    "friendzoned": "placed in friend category",
    "rizz": "charm or charisma",
    "rizzing": "charming someone",
    "rizzed": "charmed someone",
    "rizzed up": "successfully charmed",
    "rizz up": "to charm someone",
    "unspoken rizz": "natural charm without words",
    "w rizz": "great charm",
    "L rizz": "no charm",
    "no rizz": "no charm",
    "rizzler": "charming person",
    "rizzy": "charming",
    "gyatt": "exclamation of attraction",
    "gyat": "exclamation of attraction",
    "caught feelings": "developed romantic feelings",
    "feelings": "romantic emotions",
    "ship": "support a romantic couple",
    "shipped": "supported a romantic couple",
    "shipping": "supporting a romantic couple",
    "otp": "one true pair",
    "canon": "officially confirmed",
    "headcanon": "personal fan theory",
    "fanfic": "fan written fiction",
    "ff": "fanfiction",
    "smut": "explicit fan fiction",
    "fluff": "sweet romantic fan fiction",
    "angst": "emotional sad fan fiction",
    "slow burn": "gradual romance",
    "enemies to lovers": "romance trope",
    "friends to lovers": "romance trope",
    "toxic": "harmful relationship dynamic",
    "red flag": "warning sign in relationship",
    "red flags": "warning signs in relationship",
    "green flag": "positive sign in relationship",
    "green flags": "positive signs in relationship",
    "ick": "sudden feeling of dislike",
    "the ick": "sudden feeling of dislike",
    "got the ick": "developed sudden dislike",
    "gave me the ick": "made me suddenly dislike them",
    "butterflies": "nervous excitement from crush",
    "heart eyes": "deeply attracted",
    "down bad": "desperately attracted to someone",
    "down horrendous": "extremely attracted to someone",
    "obsessed": "deeply attracted",
    "fixated": "intensely focused on someone",
    "whipped": "completely devoted to partner",
    "soft": "gentle or emotionally vulnerable",
    "soft launch": "subtly introducing partner online",
    "hard launch": "publicly introducing partner online",
    "launched": "introduced relationship publicly",

    # ─────────────────────────────────────────
    # MODERN GEN Z / GEN ALPHA SLANG
    # ─────────────────────────────────────────
    "hits different": "feels uniquely special",
    "rent free": "constantly on your mind",
    "no thoughts": "empty minded",
    "understood the assignment": "performed perfectly",
    "giving": "resembling or feeling like",
    "it is giving": "it resembles or feels like",
    "ate and left no crumbs": "did something perfectly",
    "ate": "did something perfectly",
    "ate that": "did that perfectly",
    "we love to see it": "expressing approval",
    "not me": "embarrassingly i am doing this",
    "living rent free": "constantly thinking about",
    "caught in 4k": "caught doing something clearly",
    "delulu": "delusional",
    "delulu is the solulu": "delusion is the solution",
    "rizz": "charm or charisma",
    "gyatt": "exclamation of attraction",
    "fanum tax": "stealing food from someone",
    "sigma": "independent lone wolf person",
    "alpha": "dominant leader",
    "beta": "follower type",
    "omega": "last or lowest rank",
    "grindset": "hard work mindset",
    "gym bro": "fitness enthusiast",
    "gains": "muscle growth",
    "swole": "very muscular",
    "ripped": "very muscular",
    "shredded": "very lean muscular",
    "bulking": "eating to gain muscle",
    "cutting": "dieting to lose fat",
    "glowup": "impressive transformation",
    "glow up": "impressive transformation",
    "glowed up": "transformed impressively",
    "era": "current phase of life",
    "in my era": "currently in a phase",
    "girl dinner": "minimal effortless meal",
    "girl math": "creative personal logic",
    "boy math": "male version of personal logic",
    "roman empire": "thing you think about often",
    "very demure": "very modest and reserved",
    "very mindful": "very thoughtful",
    "brat": "carefree rebellious attitude",
    "brat summer": "carefree summer attitude",
    "aura": "cool energy or vibe",
    "aura points": "coolness score",
    "main character energy": "confident self centered energy",
    "vibe check": "assessing the mood",
    "passed the vibe check": "has good energy",
    "failed the vibe check": "has bad energy",
    "npc behavior": "acting robotic or predictable",
    "caught lacking": "caught off guard unprepared",
    "brain rot": "mind numbing content",
    "brainrot": "mind numbing content",
    "this is fine": "sarcastic everything is bad",
    "we are so back": "things are good again",
    "it is so over": "things are hopeless",
    "cooked": "in serious trouble or done",
    "no shot": "no way that happened",
    "understood": "got it",
    "sending me": "making me laugh hard",
    "hollering": "laughing loudly",
    "iykyk": "if you know you know",
    "rent free": "always on your mind",
    "slay queen": "you are doing amazing",
    "mother": "iconic inspirational person",
    "iconic": "memorable and impressive",
    "serve": "impress or deliver",
    "serving looks": "looking great",
    "drag": "criticize harshly",
    "dragged": "criticized harshly",
    "clap back": "respond sharply",
    "receipts": "proof or evidence",
    "no tea no shade": "no offense",
    "throwing shade": "disrespecting subtly",
    "snatched my wig": "shocked me",
    "wig": "amazed",
    "pressed": "upset or bothered",
    "heated": "angry",
    "unhinged": "wild or crazy",
    "delusional": "out of touch with reality",
    "chronically online": "always on the internet",
    "terminally online": "always on the internet",
    "posting": "sharing content online",
    "not the": "expressing disbelief",
    "the way": "expressing disbelief or amusement",
    "imagine": "i cannot believe this",
    "bestie no": "friend please do not",
    "bestie yes": "friend please do this",
    "ok bestie": "okay friend",
    "thanks bestie": "thank you friend",
    "periodt bestie": "end of discussion friend",
    "we do not do that here": "that is not acceptable",
    "as a treat": "something special occasionally",
    "for the plot": "because it makes life interesting",
    "plot twist": "unexpected turn of events",
    "plot armor": "unrealistic survival in story",
    "character development": "personal growth",
    "lore": "backstory or history",
    "lore drop": "revealing backstory",
    "origin story": "how something started",
    "redemption arc": "improving after mistakes",
    "villain era": "acting selfishly or badly",
    "main character syndrome": "thinking you are the protagonist",
    "side character": "unimportant person",
    "background character": "very unimportant person",
    "rent free in my head": "cannot stop thinking about it",
    "intrusive thoughts": "unwanted random thoughts",
    "hyperfixation": "intense obsessive interest",
    "fixation": "obsessive interest",
    "infodump": "share a lot of information at once",
    "info dump": "share excessive information",
    "tangent": "go off topic",
    "rabbit hole": "deep exploration of a topic",
    "down the rabbit hole": "deeply exploring a topic",
    "spiral": "get increasingly anxious or obsessed",
    "spiraling": "getting increasingly anxious",
    "doom": "feel hopeless",
    "dooming": "feeling hopeless",
    "venting": "expressing feelings",
    "vent": "express feelings",
    "trauma dump": "share trauma unexpectedly",
    "word vomit": "saying things without thinking",
    "word dump": "share many thoughts at once",
    "brain dump": "write all thoughts down",
    "hot take": "controversial opinion",
    "cold take": "obvious uncontroversial opinion",
    "take": "opinion",
    "spicy take": "controversial opinion",
    "unpopular opinion": "uncommon view",
    "popular opinion": "common view",
    "opinion": "personal view",

    # ─────────────────────────────────────────
    # TECH & GAMING SLANG
    # ─────────────────────────────────────────
    "gg": "good game",
    "ggwp": "good game well played",
    "wp": "well played",
    "gl": "good luck",
    "glhf": "good luck have fun",
    "hf": "have fun",
    "lfg": "looking for group",
    "lf": "looking for",
    "lf1m": "looking for one more",
    "hp": "health points",
    "xp": "experience points",
    "gg ez": "easy game",
    "ez": "easy",
    "noob": "beginner",
    "n00b": "beginner",
    "newb": "newbie",
    "newbie": "new player",
    "pro": "professional or skilled",
    "tryhard": "someone who tries very hard",
    "griefer": "player who ruins fun",
    "toxic": "negative or mean behavior",
    "meta": "most effective tactics available",
    "nerf": "weaken",
    "buff": "strengthen",
    "lag": "slow connection",
    "dc": "disconnected",
    "fps": "frames per second",
    "clan": "game group",
    "bot": "automated player",
    "hack": "cheat",
    "mod": "moderator or modification",
    "dlc": "downloadable content",
    "rng": "random number generator",
    "respawn": "come back to life in game",
    "spawn": "appear in game",
    "spawn kill": "kill immediately after appearing",
    "camp": "stay in one spot",
    "camper": "player who stays in one spot",
    "camping": "staying in one spot",
    "rush": "attack quickly",
    "rushing": "attacking quickly",
    "snipe": "shoot from far away",
    "sniper": "player who shoots from far away",
    "sniping": "shooting from far away",
    "one shot": "kill in one hit",
    "one tap": "kill in one shot",
    "clutch": "winning in difficult situation",
    "clutched": "won in difficult situation",
    "clutch up": "perform under pressure",
    "ace": "kill entire enemy team",
    "headshot": "hit to the head",
    "hs": "headshot",
    "insta kill": "instant kill",
    "instakill": "instant kill",
    "overpowered": "too strong",
    "op": "overpowered",
    "underpowered": "too weak",
    "broken": "overpowered or unfair",
    "busted": "overpowered or unfair",
    "nerfed": "made weaker",
    "buffed": "made stronger",
    "patched": "fixed or updated",
    "hotfix": "quick update",
    "update": "new version",
    "patch": "update or fix",
    "season": "timed game period",
    "rank": "competitive level",
    "ranked": "competitive mode",
    "unranked": "casual mode",
    "casual": "non competitive mode",
    "comp": "competitive",
    "competitive": "playing to win",
    "leaderboard": "ranking chart",
    "kda": "kills deaths assists",
    "k/d": "kill death ratio",
    "win rate": "percentage of wins",
    "winrate": "percentage of wins",
    "mmr": "matchmaking rating",
    "elo": "skill rating",
    "grind": "play a lot to improve",
    "grinding": "playing a lot to improve",
    "farm": "collect resources",
    "farming": "collecting resources",
    "loot": "items or rewards",
    "looting": "collecting items",
    "drop": "fall to starting location",
    "hot drop": "land in busy area",
    "hot zone": "busy dangerous area",
    "safe zone": "safe area in game",
    "zone": "game boundary area",
    "circle": "shrinking game boundary",
    "storm": "dangerous area outside boundary",
    "endgame": "final phase of game",
    "final circle": "last game boundary",
    "win condition": "how to win",
    "loss condition": "how to lose",
    "strat": "strategy",
    "strategy": "plan for winning",
    "tactic": "specific move",
    "playstyle": "way of playing",
    "carry": "lead team to victory",
    "carrying": "leading team to victory",
    "hard carry": "single handedly winning",
    "throw": "lose when winning",
    "throwing": "losing when winning",
    "int": "intentionally lose",
    "inting": "intentionally losing",
    "feed": "give kills to enemy",
    "feeding": "giving kills to enemy",
    "tilted": "frustrated and playing badly",
    "tilt": "frustration affecting play",
    "rage quit": "quit in anger",
    "rage quitting": "quitting in anger",
    "afk": "away from keyboard",
    "dc": "disconnected",
    "reconnecting": "connecting again",
    "ddos": "cyberattack",
    "stream": "live broadcast",
    "streaming": "live broadcasting",
    "streamer": "live broadcaster",
    "viewer": "stream watcher",
    "chat": "stream comments",
    "sub": "subscriber",
    "donate": "give money to streamer",
    "bits": "twitch currency",
    "gems": "in game currency",
    "coins": "in game currency",
    "tokens": "in game currency",
    "vbucks": "fortnite currency",
    "robux": "roblox currency",
    "skins": "character cosmetics",
    "cosmetics": "visual customizations",
    "drip": "stylish outfit or gear",
    "fit check": "checking your outfit",
    "loadout": "equipment setup",
    "build": "character or equipment configuration",
    "meta build": "most effective configuration",
    "off meta": "unconventional configuration",
    "gank": "ambush attack",
    "ganked": "ambush attacked",
    "gank squad": "ambush group",
    "rotation": "moving to different area",
    "rotating": "moving to different area",
    "rotation route": "path for moving",
    "pinch": "attack from both sides",
    "third party": "attack two fighting groups",
    "third partied": "attacked while already fighting",
    "juke": "evade or trick enemy",
    "juked": "evaded enemy",
    "baited": "tricked into bad position",
    "bait": "trick someone",
    "outplayed": "defeated with superior skill",
    "outplay": "defeat with superior skill",
    "misplay": "make a mistake",
    "misplayed": "made a mistake",
    "macro": "overall game strategy",
    "micro": "individual skill mechanics",
    "mechanics": "technical skill",
    "aim": "targeting skill",
    "aim assist": "automatic targeting help",
    "crosshair": "targeting reticle",
    "recoil": "weapon kickback",
    "spray": "automatic fire",
    "burst": "short automatic fire",
    "semi": "semi automatic fire",
    "full auto": "fully automatic fire",
    "reload": "refill ammunition",
    "ammo": "ammunition",
    "mag": "ammunition magazine",
    "clip": "ammunition clip",
    "inventory": "items you carry",
    "backpack": "inventory storage",
    "stash": "stored items",
    "drop": "leave items on ground",
    "ping": "mark location or connection speed",
    "pinging": "marking location",
    "call out": "announce enemy location",
    "callout": "location name",
    "info": "enemy information",
    "intel": "enemy information",
    "map awareness": "knowing enemy positions",
    "minimap": "small map display",
    "hud": "heads up display",
    "ui": "user interface",
    "fps": "first person shooter or frames per second",
    "tps": "third person shooter",
    "rpg": "role playing game",
    "mmo": "massively multiplayer online game",
    "moba": "multiplayer online battle arena",
    "br": "battle royale",
    "rts": "real time strategy",
    "pvp": "player versus player",
    "pve": "player versus environment",
    "co-op": "cooperative play",
    "coop": "cooperative play",
    "solo": "playing alone",
    "duo": "playing in pair",
    "trio": "playing in group of three",
    "squad": "playing in group of four",
    "party": "group of players",
    "lobby": "pre game waiting area",
    "queue": "waiting for match",
    "matchmaking": "finding opponents",
    "server": "game host computer",
    "lag": "slow connection delay",
    "latency": "connection delay",
    "ms": "milliseconds of delay",
    "ping": "connection speed in ms",
    "rubber banding": "jerky movement from lag",
    "desync": "connection timing mismatch",
    "crash": "game stops working",
    "bug": "game error",
    "glitch": "game error",
    "exploit": "use game error to advantage",
    "cheat": "use unauthorized advantage",
    "aimbot": "automatic aiming cheat",
    "wallhack": "see through walls cheat",
    "speedhack": "move faster cheat",
    "maphack": "see full map cheat",
    "modded": "modified game",
    "vanilla": "unmodified game",
    "sandbox": "open creative mode",
    "creative": "creative building mode",
    "survival": "survival game mode",
    "hardcore": "difficult permanent death mode",

    # ─────────────────────────────────────────
    # COMPLIMENTS & EXPRESSIONS
    # ─────────────────────────────────────────
    "legend": "amazing person",
    "king": "great person male",
    "queen": "great person female",
    "chad": "confident alpha male",
    "sigma male": "independent lone wolf",
    "gigachad": "extremely confident male",
    "based": "admirable or agreeable",
    "redpilled": "aware of harsh truth",
    "bluepilled": "unaware of harsh truth",
    "black pilled": "extremely pessimistic",
    "pill": "perspective or worldview",
    "sheesh": "expression of amazement",
    "sheeesh": "strong expression of amazement",
    "drippy": "very stylish",
    "drip": "stylish fashion",
    "swag": "style and confidence",
    "swagged out": "very stylish",
    "fresh": "stylish or new",
    "clean": "stylish or neat",
    "crispy": "very clean or stylish",
    "fly": "stylish",
    "dope": "amazing or cool",
    "dopest": "most amazing",
    "tight": "very good",
    "sick": "amazing",
    "wicked": "amazing",
    "gnarly": "amazing or extreme",
    "radical": "amazing",
    "rad": "amazing",
    "tubular": "amazing",
    "groovy": "cool or stylish",
    "far out": "amazing",
    "out of sight": "amazing",
    "solid": "very good",
    "choice": "very good",
    "ace": "excellent",
    "brill": "brilliant",
    "smashing": "great",
    "cracking": "excellent",
    "banging": "excellent",
    "mint": "perfect",
    "lush": "lovely",
    "class": "excellent",
    "mega": "very or extremely good",
    "boss": "excellent or in charge",
    "champ": "champion",
    "champs": "champions",
    "baller": "excellent person",
    "ballin": "living luxuriously",
    "ballin out": "living very luxuriously",
    "stunting": "showing off",
    "stunt": "show off",
    "flexing": "showing off",
    "showing out": "performing impressively",
    "went off": "performed impressively",
    "cooked": "defeated completely",
    "bodied": "defeated completely",
    "destroyed": "defeated completely",
    "wrecked": "defeated completely",
    "demolished": "defeated completely",
    "murked": "defeated completely",
    "slapped": "defeated easily",
    "mopped": "defeated easily",
    "swept": "defeated without losing",
    "shutout": "win without opponent scoring",
    "dominated": "controlled completely",
    "owned": "defeated completely",
    "pwned": "defeated completely",

    # ─────────────────────────────────────────
    # WORKOUT / FITNESS SLANG
    # ─────────────────────────────────────────
    "gym bro": "fitness enthusiast",
    "gains": "muscle growth",
    "swole": "very muscular",
    "ripped": "very lean muscular",
    "shredded": "extremely lean muscular",
    "jacked": "very muscular",
    "yoked": "very muscular",
    "diesel": "very muscular",
    "swole af": "extremely muscular",
    "gains goblin": "something stopping your gains",
    "natty": "natural without steroids",
    "juiced": "using steroids",
    "ped": "performance enhancing drug",
    "pre-workout": "energy supplement",
    "pre": "pre-workout supplement",
    "protein": "muscle building nutrient",
    "shake": "protein drink",
    "whey": "whey protein",
    "creatine": "muscle supplement",
    "macro": "macronutrient",
    "macros": "macronutrients",
    "calorie deficit": "eating less than burning",
    "calorie surplus": "eating more than burning",
    "bulk": "muscle building phase",
    "cut": "fat loss phase",
    "shred": "fat loss phase",
    "lean bulk": "gradual muscle building",
    "dirty bulk": "eating anything to gain mass",
    "clean bulk": "eating healthy to gain mass",
    "cardio": "cardiovascular exercise",
    "liss": "low intensity steady state cardio",
    "hiit": "high intensity interval training",
    "rep": "repetition",
    "reps": "repetitions",
    "set": "group of repetitions",
    "sets": "groups of repetitions",
    "pr": "personal record",
    "pb": "personal best",
    "one rep max": "maximum weight lifted once",
    "1rm": "one rep maximum",
    "pump": "muscle blood flow feeling",
    "pumped": "muscles full of blood",
    "sore": "muscle pain after exercise",
    "doms": "delayed onset muscle soreness",
    "rest day": "day without exercise",
    "recovery": "healing after exercise",
    "stretch": "flexibility exercise",
    "warm up": "preparation exercise",
    "cool down": "post exercise recovery",
    "spot": "assist with exercise",
    "spotter": "exercise assistant",
    "form": "exercise technique",
    "good form": "proper exercise technique",
    "bad form": "improper exercise technique",
    "ego lift": "lift more than you can handle",
    "ego lifting": "lifting more than you can handle",
    "squat": "leg exercise",
    "deadlift": "full body exercise",
    "bench": "chest exercise",
    "ohp": "overhead press",
    "row": "back exercise",
    "pull up": "back and arm exercise",
    "push up": "chest and arm exercise",
    "dip": "tricep exercise",
    "curl": "bicep exercise",
    "extension": "tricep exercise",
    "raise": "shoulder exercise",
    "fly": "chest or shoulder exercise",
    "press": "pushing exercise",
    "pull": "pulling exercise",
    "push": "pushing exercise",
    "leg day": "leg exercise day",
    "chest day": "chest exercise day",
    "back day": "back exercise day",
    "arm day": "arm exercise day",
    "shoulder day": "shoulder exercise day",
    "core day": "core exercise day",
    "skip leg day": "avoid leg exercises",
    "skipping leg day": "avoiding leg exercises",
    "bro split": "different muscle each day",
    "ppl": "push pull legs split",
    "upper lower": "upper and lower body split",
    "full body": "workout all muscles",

    # ─────────────────────────────────────────
    # FOOD & DRINK SLANG
    # ─────────────────────────────────────────
    "chow": "food",
    "grub": "food",
    "eats": "food",
    "noms": "delicious food",
    "nom nom": "eating deliciously",
    "yum": "delicious",
    "yummy": "very delicious",
    "yumm": "very delicious",
    "munch": "eat or snack",
    "munching": "eating or snacking",
    "snack": "small food or attractive person",
    "snacc": "attractive person",
    "meal": "attractive person",
    "dummy thicc": "very attractive",
    "full send": "go all out",
    "send it": "go for it",
    "feast": "large meal",
    "binge": "eat or consume a lot",
    "binging": "eating or consuming a lot",
    "pig out": "eat a lot",
    "pigging out": "eating a lot",
    "stuff your face": "eat a lot",
    "inhale": "eat very fast",
    "devour": "eat quickly and completely",
    "scarf": "eat quickly",
    "scarfing": "eating quickly",
    "wolf down": "eat very fast",
    "wolfing": "eating very fast",
    "chug": "drink quickly",
    "chugging": "drinking quickly",
    "sip": "drink slowly",
    "sipping": "drinking slowly",
    "sipping tea": "enjoying gossip",
    "spill": "share gossip",
    "tea": "gossip",
    "girl dinner": "minimal meal for one",
    "situational eating": "eating based on mood",
    "comfort food": "food that makes you feel better",
    "treat yourself": "indulge yourself",
    "cheat meal": "unhealthy meal during diet",
    "cheat day": "unhealthy eating day during diet",
    "foodie": "food enthusiast",
    "food coma": "sleepy after eating too much",
    "hangry": "angry from hunger",
    "hanger": "anger from hunger",
    "starving": "very hungry",
    "famished": "very hungry",
    "ravenous": "extremely hungry",
    "parched": "very thirsty",
    "dehydrated": "need water",
    "hydrate": "drink water",
    "hydrating": "drinking water",
    "sober": "not drinking alcohol",
    "drunk": "intoxicated from alcohol",
    "tipsy": "slightly drunk",
    "buzzed": "slightly drunk",
    "hammered": "very drunk",
    "plastered": "very drunk",
    "wasted": "very drunk",
    "smashed": "very drunk",
    "lit": "drunk or amazing",
    "turnt": "excited or drunk",
    "turnt up": "excited or drunk",

    # ─────────────────────────────────────────
    # SCHOOL & STUDY SLANG
    # ─────────────────────────────────────────
    "hw": "homework",
    "hmwk": "homework",
    "hwork": "homework",
    "assgn": "assignment",
    "proj": "project",
    "pres": "presentation",
    "exam": "examination",
    "quiz": "short test",
    "test": "examination",
    "finals": "final examinations",
    "midterm": "middle of term exam",
    "paper": "written assignment",
    "essay": "written assignment",
    "thesis": "long research paper",
    "dissertation": "doctoral research paper",
    "cite": "reference a source",
    "citations": "source references",
    "plagiarism": "copying without credit",
    "paraphrase": "rewrite in own words",
    "summarize": "write briefly",
    "gpa": "grade point average",
    "grade": "academic score",
    "pass": "achieve minimum grade",
    "fail": "not achieve minimum grade",
    "ace": "get perfect score",
    "bomb": "do very poorly or very well",
    "bombed": "did very poorly",
    "aced": "got perfect score",
    "cramming": "studying intensively last minute",
    "cram": "study intensively last minute",
    "all nighter": "staying up all night studying",
    "pulling an all nighter": "staying up all night",
    "study session": "period of studying",
    "study group": "group studying together",
    "tutor": "private teacher",
    "tutoring": "private teaching",
    "lecture": "professor talk",
    "seminar": "small class discussion",
    "lab": "laboratory class",
    "tutorial": "guided learning session",
    "prof": "professor",
    "teacher": "instructor",
    "instructor": "teacher",
    "ta": "teaching assistant",
    "student": "person studying",
    "grad": "graduate",
    "undergrad": "undergraduate student",
    "freshman": "first year student",
    "sophomore": "second year student",
    "junior": "third year student",
    "senior": "fourth year student",
    "alumni": "former student",
    "grad school": "graduate school",
    "uni": "university",
    "college": "higher education institution",
    "campus": "school grounds",
    "dorm": "dormitory",
    "roomie": "roommate",
    "roommate": "person sharing room",
    "housing": "accommodation",
    "financial aid": "education funding help",
    "scholarship": "merit based funding",
    "internship": "work experience program",
    "intern": "work experience participant",
    "job": "employment",
    "career": "long term employment path",
    "resume": "job application document",
    "cv": "curriculum vitae",
    "cover letter": "job application letter",
    "interview": "job application meeting",
    "hired": "got the job",
    "fired": "lost the job",
    "quit": "leave job voluntarily",

    # ─────────────────────────────────────────
    # MONEY & FINANCIAL SLANG
    # ─────────────────────────────────────────
    "broke": "having no money",
    "brokie": "person with no money",
    "rich": "having a lot of money",
    "loaded": "very rich",
    "balling": "living luxuriously",
    "paper": "money",
    "bread": "money",
    "dough": "money",
    "cash": "money",
    "guap": "money",
    "gucci": "good or money",
    "bag": "money or opportunity",
    "bags": "large amount of money",
    "secure the bag": "get the money or opportunity",
    "chase the bag": "pursue money",
    "bag secured": "money obtained",
    "finesse": "cleverly obtain money",
    "hustle": "work hard to earn money",
    "hustling": "working hard to earn money",
    "side hustle": "extra income source",
    "grind": "work hard",
    "grinding": "working hard",
    "on the grind": "working hard",
    "stack": "save money",
    "stacking": "saving money",
    "stacks": "large amount of money",
    "bands": "thousands of dollars",
    "racks": "thousands of dollars",
    "milli": "million dollars",
    "bill": "one hundred dollars",
    "buck": "one dollar",
    "fiver": "five dollars",
    "tenner": "ten dollars",
    "twenty": "twenty dollars",
    "fifty": "fifty dollars",
    "hundo": "one hundred dollars",
    "grand": "one thousand dollars",
    "splurge": "spend lavishly",
    "splurging": "spending lavishly",
    "frugal": "careful with money",
    "cheap": "not wanting to spend money",
    "penny pincher": "very careful with money",
    "tightwad": "very careful with money",
    "spendthrift": "spends money carelessly",
    "invest": "put money for future return",
    "investing": "putting money for future return",
    "crypto": "cryptocurrency",
    "bitcoin": "digital currency",
    "nft": "non fungible token",
    "hodl": "hold cryptocurrency long term",
    "to the moon": "price will rise dramatically",
    "diamond hands": "holding investment through losses",
    "paper hands": "selling investment early",
    "yolo": "risky all in investment",
    "degen": "risky investor",
    "ape in": "invest without research",
    "fud": "fear uncertainty doubt",
    "fomo": "fear of missing out on investment",
    "pump and dump": "artificially inflate then sell",
    "rugpull": "scam investment",
    "whale": "large investor",
    "lambo": "expensive car as investment goal",
    "when lambo": "when will investment make me rich",
    "gm": "good morning used in crypto community",
    "wagmi": "we are all gonna make it",
    "ngmi": "not gonna make it",

    # ─────────────────────────────────────────
    # GENERAL EXPRESSIONS
    # ─────────────────────────────────────────
    "noyb": "none of your business",
    "myob": "mind your own business",
    "stfu": "please be quiet",
    "gtfo": "get out",
    "tfw": "that feeling when",
    "mfw": "my face when",
    "ikwym": "i know what you mean",
    "wywh": "wish you were here",
    "hand": "have a nice day",
    "hagd": "have a great day",
    "hags": "have a great summer",
    "hagn": "have a great night",
    "hhoj": "ha ha only joking",
    "nsfw": "not safe for work",
    "nsfl": "not safe for life",
    "ootl": "out of the loop",
    "loop": "informed about situation",
    "in the loop": "informed about situation",
    "out of the loop": "not informed about situation",
    "catch up": "get updated on information",
    "update": "new information",
    "lowdown": "detailed information",
    "scoop": "latest information",
    "deets": "details",
    "details": "specific information",
    "tl;dr": "too long didn't read",
    "tldr": "too long didn't read",
    "in a nutshell": "briefly summarized",
    "long story short": "to summarize briefly",
    "lss": "long story short",
    "to make a long story short": "briefly",
    "bottom line": "most important point",
    "upshot": "final result",
    "gist": "main point",
    "meat": "main content",
    "crux": "main point",
    "point": "main idea",
    "point being": "the reason is",
    "anyway": "regardless",
    "anywho": "regardless",
    "anyhoo": "regardless",
    "regardless": "no matter what",
    "nevertheless": "despite that",
    "however": "but",
    "but": "however",
    "although": "even though",
    "even so": "despite that",
    "that said": "however",
    "that being said": "however",
    "having said that": "however",
    "in any case": "regardless",
    "either way": "regardless of choice",
    "at any rate": "regardless",
    "in any event": "regardless",
    "come what may": "no matter what happens",
    "for what its worth": "this might be useful",
    "for the record": "to state clearly",
    "off the record": "unofficially",
    "on the record": "officially",
    "technically speaking": "to be precise",
    "speaking of which": "related to that",
    "on that note": "related to that",
    "while we're at it": "since we are doing this",
    "while im at it": "since i am doing this",
    "not to mention": "additionally",
    "let alone": "not even considering",
    "to say nothing of": "not even mentioning",
    "much less": "even less likely",
    "let alone": "not even",
    "forget about it": "it is impossible or forget it",
    "fuhgeddaboudit": "forget about it",
    "no way": "impossible",
    "no way jose": "absolutely impossible",
    "not a chance": "absolutely not",
    "fat chance": "very unlikely",
    "slim chance": "very unlikely",
    "long shot": "very unlikely",
    "million to one": "very unlikely",
    "against all odds": "despite being very unlikely",
    "against the odds": "despite being unlikely",
    "defying the odds": "succeeding despite being unlikely",
    "beat the odds": "succeeded despite being unlikely",
    "odds are": "it is likely that",
    "chances are": "it is likely that",
    "in all likelihood": "very probably",
    "in all probability": "very probably",
    "odds on": "very likely",
    "ten to one": "very likely",

    # ─────────────────────────────────────────
    # TIME & URGENCY
    # ─────────────────────────────────────────
    "asap": "as soon as possible",
    "stat": "immediately",
    "pronto": "immediately",
    "rn": "right now",
    "atm": "at the moment",
    "rq": "real quick",
    "irl": "in real life",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "fwiw": "for what it is worth",
    "tbh": "to be honest",
    "ngl": "not gonna lie",
    "smh": "shaking my head",
    "brb": "be right back",
    "bbs": "be back soon",
    "bbl": "be back later",
    "afk": "away from keyboard",
    "omw": "on my way",
    "otw": "on the way",
    "eta": "estimated time of arrival",
    "b4": "before",
    "2day": "today",
    "2moro": "tomorrow",
    "2nite": "tonight",
    "l8r": "later",
    "latur": "later",
    "eventually": "at some point",
    "whenever": "at any time",
    "whenever you can": "no rush",
    "no rush": "take your time",
    "take your time": "no hurry",
    "hurry up": "be quick",
    "quick": "fast",
    "rush": "hurry",
    "snap": "do quickly",
    "chop chop": "hurry up",
    "get a move on": "hurry up",
    "step on it": "hurry up",
    "time is money": "do not waste time",
    "clock is ticking": "hurry up",
    "running out of time": "almost too late",
    "last minute": "at the very end",
    "last second": "at the very last moment",
    "just in time": "barely on time",
    "barely made it": "just in time",
    "fashionably late": "intentionally or acceptably late",
    "better late than never": "arriving late is better than not arriving",

    # ─────────────────────────────────────────
    # MISCELLANEOUS INTERNET CULTURE
    # ─────────────────────────────────────────
    "meme": "internet joke or image",
    "memes": "internet jokes or images",
    "viral meme": "widely shared joke",
    "dank meme": "very good internet joke",
    "deep fried meme": "heavily edited distorted meme",
    "normie": "mainstream person",
    "edgy": "provocatively unconventional",
    "cringe": "embarrassing content",
    "based": "cool or admirable",
    "cope": "deal with disappointment",
    "copium": "fictional drug for coping",
    "seethe": "be very angry",
    "dilate": "insulting dismissal",
    "rent free": "living in someone's head",
    "skill issue": "your fault for being bad",
    "touch grass": "go outside",
    "get some air": "go outside",
    "go outside": "stop being online",
    "log off": "stop using internet",
    "log on": "start using internet",
    "lurk more": "observe before participating",
    "newfag": "new community member",
    "oldfag": "longtime community member",
    "anon": "anonymous person",
    "doxx": "reveal personal information",
    "doxxed": "personal information revealed",
    "troll": "deliberately provoke people",
    "trolling": "deliberately provoking people",
    "troll face": "trolling expression",
    "rick roll": "prank link to rick astley song",
    "rick rolled": "pranked with rick astley link",
    "bait": "provocative content to get reactions",
    "taking the bait": "reacting to provocation",
    "don't take the bait": "ignore the provocation",
    "don't feed the trolls": "ignore provocateurs",
    "flame war": "angry online argument",
    "drama": "conflict or scandal",
    "beef": "conflict between people",
    "diss": "disrespect or criticize",
    "dis": "disrespect or criticize",
    "dissed": "disrespected or criticized",
    "dissing": "disrespecting or criticizing",
    "roast": "mock or insult humorously",
    "roasted": "mocked or insulted humorously",
    "roasting": "mocking or insulting humorously",
    "clowned": "embarrassed or mocked",
    "clowning": "embarrassing or mocking",
    "clown": "fool or mock",
    "fool": "trick or naive person",
    "played": "tricked or fooled",
    "got played": "was tricked",
    "scammed": "was deceived for money",
    "scam": "deceptive scheme",
    "catfish": "fake online identity",
    "catfished": "deceived by fake identity",
    "finsta": "fake or private instagram",
    "burner": "temporary anonymous account",
    "alt": "alternative account",
    "main": "primary account",
    "throwaway": "temporary account",
    "fake deep": "pretending to be profound",
    "pseudo": "fake or false",
    "poser": "someone pretending to be something",
    "poseur": "someone pretending to be something",
    "wannabe": "someone who wants to be something",
    "try hard": "someone trying too hard to be cool",
    "edgelord": "someone trying to be edgy",
    "incel": "involuntary celibate person",
    "femcel": "female involuntary celibate person",
    "volcel": "voluntary celibate person",
    "mgtow": "men going their own way movement",
    "redpill": "harsh truth perspective",
    "bluepill": "comfortable ignorance perspective",
    "blackpill": "extreme pessimistic perspective",
    "whitepill": "optimistic hopeful perspective",
    "doomer": "extremely pessimistic person",
    "bloomer": "optimistic thriving person",
    "boomer": "baby boomer generation person",
    "millennial": "generation y person",
    "zoomer": "generation z person",
    "gen alpha": "generation after z",
    "gen z": "generation born late 1990s to 2010s",
    "gen x": "generation born 1965 to 1980",
    "baby boomer": "generation born 1946 to 1964",
    "silent generation": "generation born 1928 to 1945",
    "greatest generation": "generation born before 1928",

    # ─────────────────────────────────────────
    # BRITISH / AUSTRALIAN / REGIONAL SLANG
    # ─────────────────────────────────────────
    "bloke": "man",
    "bird": "girl",
    "mate": "friend",
    "lad": "young man",
    "lass": "young woman",
    "cheeky": "slightly rude but funny",
    "dodgy": "suspicious or unreliable",
    "gutted": "very disappointed",
    "chuffed": "very pleased",
    "knackered": "very tired",
    "gobsmacked": "very shocked",
    "bloody": "very or emphasis word",
    "blimey": "expression of surprise",
    "crikey": "expression of surprise",
    "cor blimey": "strong expression of surprise",
    "brilliant": "excellent",
    "brill": "brilliant",
    "rubbish": "nonsense or garbage",
    "bollocks": "nonsense",
    "codswallop": "nonsense",
    "piffle": "nonsense",
    "twaddle": "nonsense",
    "miffed": "annoyed",
    "shirty": "annoyed",
    "narked": "annoyed",
    "hacked off": "annoyed",
    "cheesed off": "annoyed",
    "brassed off": "annoyed",
    "fed up": "annoyed",
    "done in": "very tired",
    "shattered": "very tired",
    "zonked": "very tired",
    "kip": "sleep",
    "kipping": "sleeping",
    "faffing": "wasting time",
    "faff": "waste time",
    "skiving": "avoiding work",
    "skive": "avoid work",
    "bunk off": "skip school or work",
    "bunk": "skip",
    "wag": "skip school",
    "wagging": "skipping school",
    "mitching": "skipping school",
    "mitche": "skip school",
    "doss": "do nothing or lazy",
    "dossing": "doing nothing lazily",
    "gormless": "stupid or clueless",
    "daft": "silly or stupid",
    "thick": "stupid",
    "dim": "not very intelligent",
    "dim witted": "not very intelligent",
    "bright": "intelligent",
    "clever": "intelligent",
    "cheeky monkey": "playfully naughty person",
    "taking the mickey": "making fun of someone",
    "taking the piss": "making fun of someone",
    "on the pull": "looking for romantic partner",
    "snog": "kiss",
    "snogging": "kissing",
    "pash": "crush",
    "fit": "attractive",
    "dishy": "very attractive",
    "well fit": "very attractive",
    "proper": "very or real",
    "proper good": "very good",
    "dead good": "very good",
    "well good": "very good",
    "mint": "excellent",
    "boss": "excellent",
    "sound": "good or reliable",
    "sound as a pound": "very reliable",
    "bob's your uncle": "there you go it is done",
    "sorted": "arranged or good",
    "sorted out": "resolved",
    "cheers": "thanks or goodbye",
    "ta": "thanks",
    "ta very much": "thank you very much",
    "ta muchly": "thank you very much",
    "blinding": "excellent",
    "cracking": "excellent",
    "belting": "excellent",
    "smashing": "excellent",
    "banging": "excellent or loud",
    "lush": "lovely",
    "tidy": "attractive or good",
    "alright": "hello or okay",
    "alright mate": "hello friend",
    "you alright": "how are you",
    "innit": "isn't it",
    "init": "isn't it",
    "yeah nah": "no",
    "nah yeah": "yes",
    "reckon": "think or believe",
    "heaps": "a lot",
    "loads": "a lot",
    "lashings": "a lot",
    "stacks": "a lot",
    "oodles": "a lot",
    "tonnes": "a lot",
    "oceans": "a lot",
    "shed loads": "a lot",
    "buckets": "a lot",
    "bucket loads": "a lot",
    "chock full": "completely full",
    "jam packed": "very crowded",
    "rammed": "very crowded",
    "packed out": "very crowded",
    "manky": "disgusting or dirty",
    "minging": "disgusting",
    "grotty": "dirty or unpleasant",
    "rank": "disgusting",
    "grim": "unpleasant",
    "grot": "dirt or unpleasant place",
    "grubby": "dirty",
    "scruffy": "untidy",
    "tatty": "worn out",
    "naff": "unfashionable or poor quality",
    "pants": "very bad",
    "pony": "poor quality",
    "ropey": "poor quality",
    "duff": "broken or poor quality",
    "dud": "something that fails",
    "lemon": "defective product",
    "dodgy": "unreliable or suspicious",
    "shady": "suspicious",
    "shifty": "suspicious",
    "iffy": "doubtful or unreliable",
    "sketchy": "suspicious or unreliable",
    "bent": "dishonest or corrupt",
    "crooked": "dishonest",
    "backhander": "bribe",
    "bribe": "corrupt payment",
    "bungs": "bribes",
    "on the fiddle": "being corrupt",
    "fiddling": "being corrupt",
    "skimming": "stealing small amounts",
    "scam": "fraud",
    "con": "fraud",
    "hustle": "fraud or hard work",
    "grift": "small fraud",
    "grifter": "small fraudster",


# ─────────────────────────────────────────
# Normal use
# ─────────────────────────────────────────

    "u": "you",
    "r": "are",
    "ur": "your",
    "urs": "yours",
    "y": "why",
    "k": "okay",
    "ok": "okay",
    "thx": "thanks",
    "thanx": "thanks",
    "pls": "please",
    "plz": "please",
    "bro": "brother",
    "sis": "sister",
    "btw": "by the way",
    "idk": "i do not know",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "asap": "as soon as possible",
    "fyi": "for your information",
    "bff": "best friends forever",
    "tbh": "to be honest",
    "omg": "oh my god",
    "wtf": "what the fuck",
    "wth": "what the hell",
    "lol": "laugh",
    "lmao": "laugh",
    "rofl": "laugh",
    "haha": "laugh",
    "hehe": "laugh",
    "gr8": "great",
    "b4": "before",
    "luv": "love",
    "msg": "message",
    "pic": "picture",
    "sec": "second",
    "min": "minute",
    "hr": "hour",
    "abt": "about",
    "bcz": "because",
    "bc": "because",
    "cuz": "because",
    "coz": "because",
    "tho": "though",
    "thru": "through",
    "wanna": "want to",
    "gonna": "going to",
    "gotta": "got to",
    "lemme": "let me",
    "dunno": "do not know",
    "aint": "is not",
    "ya": "you",
    "yo": "you",
    "sup": "what is up",
    "wassup": "what is up",
    "brb": "be right back",
    "ttyl": "talk to you later",
    "gtg": "got to go",
    "bbl": "be back later",
    "afk": "away from keyboard",
    "np": "no problem",
    "nvm": "never mind",
    "jk": "just kidding",
    "ily": "i love you",
    "ilysm": "i love you so much",
    "xoxo": "hugs and kisses",
    "dm": "direct message",
    "tq": "thank you",
    "ty": "thank you",
    "gg": "good game",
    "gl": "good luck",
    "hf": "have fun",
    "smh": "shaking my head",
    "irl": "in real life",
    "fav": "favorite",
    "wrk": "work",
    "frm": "from",
    "nd": "and",
    "dat": "that",
    "dis": "this",
    "tmrw": "tomorrow",
    "2day": "today",
    "4u": "for you",
    "2u": "to you",
    "bday": "birthday",
    "hbd": "happy birthday",
    "gm": "good morning",
    "gn": "good night",


    # ─────────────────────────────────────────
    # SARCASM & HUMOR
    # ─────────────────────────────────────────
    "sure jan": "i do not believe you",
    "sure": "sarcastic agreement",
    "totally": "sarcastic agreement",
    "obviously": "sarcastic obviously",
    "clearly": "sarcastic obviously",
    "sure buddy": "i doubt you",
    "whatever you say": "i disagree",
    "okay sure": "i do not believe you",
    "yeah right": "i do not believe you",
    "as if": "i do not believe you",
    "not": "sarcastic negation",
    "not really": "actually no",
    "good luck with that": "i doubt you will succeed",
    "we will see": "i am skeptical",
    "tell me more": "sarcastic interest",
    "fascinating": "sarcastic interest",
    "thrilling": "sarcastic excitement",
    "riveting": "sarcastic excitement",
    "groundbreaking": "sarcastic amazement",
    "shocking": "sarcastic shock",
    "who asked": "nobody asked your opinion",
    "did i ask": "i did not ask",
    "no one cares": "nobody cares",
    "cool story bro": "i do not care",
    "cool story": "i do not care",
    "okay boomer": "dismissing old fashioned view",
    "ok boomer": "dismissing old fashioned view",
    "thanks captain obvious": "that was obvious",
    "thanks sherlock": "that was obvious",
    "no duh": "obviously",
    "no kidding": "obviously",
    "you think": "sarcastic obviously",
    "really genius": "sarcastic compliment",
    "bravo": "sarcastic applause",
    "wow thanks": "sarcastic thanks",
    "so helpful": "sarcastic thanks",
    "great job": "sarcastic praise",
    "well done": "sarcastic praise",
    "congratulations": "sarcastic congratulations",
    "congrats": "sarcastic congratulations",
    "slow clap": "sarcastic applause",
    "give this person a medal": "sarcastic praise",
    "bold of you to assume": "that assumption is wrong",
    "imagine thinking": "that thought is ridiculous",
    "the audacity": "how dare you",
    "unbelievable": "i cannot believe this",
    "incredible": "sarcastic amazement",
    "mind blowing": "sarcastic amazement",
    "life changing": "sarcastic exaggeration",
    "game changer": "significant or sarcastic",
    "revolutionary": "sarcastic amazement",
    "next level": "extremely good or sarcastic",
    "tier list": "ranking of things",
    "s tier": "best tier",
    "a tier": "very good tier",
    "b tier": "good tier",
    "c tier": "average tier",
    "d tier": "poor tier",
    "f tier": "worst tier",
    "god tier": "best possible tier",
    "trash tier": "worst possible tier",
    "mid tier": "average tier",
    "bottom tier": "worst tier",
    "top tier": "best tier",

    
    # Numbers & Letters as Words
    "1": "one",
    "2gether": "together",
    "3sum": "threesome",
    "4u": "for you",
    "4real": "for real",
    "10q": "thank you",
    "b4n": "bye for now",
    "cu2": "see you too",
    "gr8t": "great",
    "h2g": "have to go",
    "j2lyk": "just to let you know",
    "j4f": "just for fun",
    "k8": "kate",
    "l8ter": "later",
    "n2m": "not too much",
    "n2b": "not too bad",
    "p8": "plate",
    "q8": "kuwait",
    "r8": "rate",
    "s8n": "satan",
    "t8": "tate",
    "u2": "you too",
    "v8": "engine or drink",
    "w8ing": "waiting",
    "x2": "times two",
    "2bad": "too bad",
    "2g2bt": "too good to be true",
    "2g2b4g": "too good to be forgotten",

    # Extended Greetings
    "sup": "what is up",
    "supp": "what is up",
    "wazzup": "what is up",
    "wassup": "what is up",
    "yo": "hello",
    "heya": "hello",
    "hiya": "hello",
    "howdy": "hello",
    "ello": "hello",
    "g'day": "good day",
    "gday": "good day",
    "gdm": "good day mate",
    "morn": "good morning",
    "nite": "good night",
    "gnite": "good night",
    "g9": "good night",
    "gd9": "good night",
    "l8r": "later",
    "latur": "later",
    "ta": "thanks",
    "cheers": "thanks",
    "thks": "thanks",
    "thnx": "thanks",
    "thnks": "thanks",
    "tks": "thanks",
    "tyvm": "thank you very much",
    "tysm": "thank you so much",
    "tyvmf": "thank you very much friend",
    "tyty": "thank you thank you",
    "tnx": "thanks",

    # Relationship & Personal
    "hubby": "husband",
    "wifey": "wife",
    "babe": "baby or loved one",
    "bb": "baby",
    "bby": "baby",
    "babes": "baby",
    "hun": "honey",
    "huns": "honey",
    "hon": "honey",
    "luv": "love",
    "luvya": "love you",
    "luvv": "love",
    "crush": "person you like",
    "ex": "ex partner",
    "exes": "ex partners",
    "s/o": "significant other",
    "so": "significant other",
    "bfgf": "boyfriend girlfriend",
    "mia": "missing in action",
    "wifed": "married",
    "dm": "direct message",
    "dms": "direct messages",
    "situationship": "undefined relationship",
    "talking": "casually dating",

    # Mood / Feelings
    "depresso": "depressed",
    "sadge": "sad",
    "hyped": "very excited",
    "hype": "excitement",
    "chillin": "relaxing",
    "chill": "relax",
    "vibing": "relaxing or enjoying",
    "shook": "shocked",
    "triggered": "upset or angered",
    "salty": "bitter or upset",
    "slay": "doing amazingly",
    "slayed": "did amazingly",
    "dead": "found extremely funny",
    "ded": "found extremely funny",
    "im dead": "that is extremely funny",
    "hollering": "laughing loudly",
    "crying": "laughing very hard",
    "screaming": "shocked or excited",
    "obsessed": "really like something",
    "living": "really enjoying",
    "ate": "did something perfectly",
    "ate that": "did that perfectly",
    "understood": "got it",
    "understood the assignment": "did perfectly",
    "sending me": "making me laugh hard",
    "deceased": "found extremely funny",

    # Agreement / Disagreement
    "fasho": "for sure",
    "fa sho": "for sure",
    "fosho": "for sure",
    "fersure": "for sure",
    "forsure": "for sure",
    "totes": "totally",
    "totez": "totally",
    "defs": "definitely",
    "absol": "absolutely",
    "absly": "absolutely",
    "nope": "no",
    "nopee": "no",
    "nty": "no thank you",
    "nahh": "no",
    "naw": "no",
    "naww": "no",
    "yas": "yes",
    "yasss": "yes",
    "yass": "yes",
    "yaaaas": "yes",
    "hellyes": "absolutely yes",
    "truee": "true",
    "tru": "true",
    "truu": "true",
    "frfr": "for real for real",
    "frrr": "for real",
    "nocap": "no lie or for real",
    "onG": "on god i swear",
    "ong": "on god i swear",
    "word": "i agree",
    "wordd": "i agree",
    "say less": "understood i agree",
    "deadass": "seriously",
    "deadazz": "seriously",
    "srsly": "seriously",
    "srs": "serious",
    "istg": "i swear to god",
    "swear": "i swear",
    "swear2g": "i swear to god",
    "pinky": "i promise",
    "promise": "i promise",

    # Asking / Questioning
    "howso": "how so",
    "wdw": "what do want",
    "wdys": "what did you say",
    "wdym": "what do you mean",
    "wdyt": "what do you think",
    "wdyd": "what did you do",
    "wdyg": "what do you got",
    "wuu2": "what are you up to",
    "wuup2": "what are you up to",
    "u up": "are you awake",
    "u ok": "are you okay",
    "ura": "you are a",
    "urs": "yours",
    "yrs": "yours",
    "hbu": "how about you",
    "hby": "how about you",
    "howbou": "how about",
    "howbow": "how about",

    # Actions & Activities
    "omw": "on my way",
    "otw": "on the way",
    "b4": "before",
    "rn": "right now",
    "rnrn": "right now right now",
    "nm": "not much",
    "nmu": "not much you",
    "ntm": "not too much",
    "jsyk": "just so you know",
    "jfyi": "just for your information",
    "jic": "just in case",
    "wip": "work in progress",
    "eta": "estimated time of arrival",
    "lmao": "laughing my head off",
    "otp": "on the phone or one true pair",
    "gtg": "got to go",
    "bbiab": "be back in a bit",
    "bbiam": "be back in a minute",
    "bbiaf": "be back in a few",
    "bbs": "be back soon",
    "brbs": "be right back soon",
    "g2b": "going to bed",
    "g2s": "going to sleep",
    "s2g": "swear to god",
    "brt": "be right there",
    "rt": "right",
    "alr": "alright",
    "aight": "alright",
    "ight": "alright",

    # Tech / Gaming Slang
    "gg": "good game",
    "ggwp": "good game well played",
    "wp": "well played",
    "gl": "good luck",
    "glhf": "good luck have fun",
    "hf": "have fun",
    "afk": "away from keyboard",
    "lfg": "looking for group",
    "lf": "looking for",
    "lf1m": "looking for one more",
    "npc": "non player character",
    "hp": "health points",
    "xp": "experience points",
    "gg ez": "easy game",
    "ez": "easy",
    "noob": "beginner",
    "n00b": "beginner",
    "newb": "newbie",
    "newbie": "new player",
    "pro": "professional or skilled",
    "tryhard": "someone who tries very hard",
    "griefer": "player who ruins fun",
    "toxic": "negative or mean behavior",
    "meta": "most effective tactics available",
    "nerf": "weaken",
    "buff": "strengthen",
    "lag": "slow connection",
    "dc": "disconnected",
    "ping": "connection speed",
    "fps": "frames per second",
    "clan": "game group",
    "bot": "automated player",
    "hack": "cheat",
    "mod": "moderator or modification",
    "dlc": "downloadable content",
    "irl": "in real life",
    "rng": "random number generator",
    "respawn": "come back to life in game",

    # Compliments & Insults (Slang)
    "goat": "greatest of all time",
    "legend": "amazing person",
    "king": "great person male",
    "queen": "great person female",
    "chad": "confident alpha male",
    "simp": "someone overly devoted",
    "npc": "boring unoriginal person",
    "pick me": "attention seeker",
    "Karen": "entitled complainer",
    "boomer": "old fashioned person",
    "zoomer": "generation z person",
    "millennial": "generation y person",
    "stan": "extreme fan",
    "fanboy": "extreme male fan",
    "fangirl": "extreme female fan",
    "hater": "someone who criticizes unfairly",
    "clout": "fame or influence",
    "flex": "show off",
    "humble": "not arrogant",
    "petty": "small minded",
    "messy": "drama causing",
    "basic": "mainstream or ordinary",
    "trash": "bad or poor quality",
    "cringe": "embarrassing",
    "cringy": "embarrassing",
    "mid": "average or mediocre",
    "meh": "average or unimpressive",
    "overrated": "not as good as people say",
    "underrated": "better than people think",
    "slept on": "underappreciated",
    "based": "admirable or agreeable",
    "redpilled": "aware of truth",
    "woke": "socially aware",

    # Miscellaneous Modern Slang
    "hits different": "feels uniquely special",
    "main character": "acting like story is about you",
    "rent free": "constantly on your mind",
    "no thoughts": "empty minded",
    "understood the assignment": "performed perfectly",
    "it is giving": "it resembles or feels like",
    "giving": "resembling or feeling like",
    "ate and left no crumbs": "did something perfectly",
    "we love to see it": "expressing approval",
    "not me": "embarrassingly i am doing this",
    "living rent free": "constantly thinking about",
    "caught in 4k": "caught doing something clearly",
    "ratio": "getting more replies than likes",
    "L": "loss or failure",
    "W": "win or success",
    "take the L": "accept defeat",
    "take the W": "accept the win",
    "big L": "major failure",
    "big W": "major success",
    "the audacity": "how dare they",
    "the nerve": "how dare they",
    "the gall": "how dare they",
    "the cheek": "how dare they",
    "lowkey": "secretly or quietly",
    "highkey": "openly or definitely",
    "real talk": "seriously speaking",
    "on sight": "immediately upon seeing",
    "on god": "i swear",
    "periodt": "that is final",
    "slay queen": "you are doing amazing",
    "mother": "iconic person",
    "iconic": "memorable and impressive",
    "serve": "impress or deliver",
    "serving looks": "looking great",
    "drag": "criticize harshly",
    "dragged": "criticized harshly",
    "clap back": "respond sharply",
    "receipts": "proof or evidence",
    "spill the tea": "share the gossip",
    "no tea no shade": "no offense",
    "throwing shade": "disrespecting subtly",
    "snatched my wig": "shocked me",
    "wig": "amazed",
    "pressed": "upset or bothered",
    "heated": "angry",
    "pressed": "annoyed",
    "unhinged": "wild or crazy",
    "delusional": "out of touch with reality",
    "delulu": "delusional",
    "delulu is the solulu": "delusion is the solution",
    "rizz": "charm or charisma",
    "rizzler": "charming person",
    "no rizz": "no charm",
    "w rizz": "great charm",
    "L rizz": "no charm",
    "gyatt": "exclamation of attraction",
    "fanum tax": "stealing food from someone",
    "sigma": "independent lone wolf person",
    "alpha": "dominant leader",
    "beta": "follower type",
    "omega": "last or lowest rank",
    "grindset": "work hard mindset",
    "gym bro": "fitness enthusiast",
    "gains": "muscle growth",
    "swole": "very muscular",
    "ripped": "very muscular",
    "shredded": "very lean muscular",
    "bulking": "eating to gain muscle",
    "cutting": "dieting to lose fat",
    "skipping leg day": "neglecting leg workouts",
    "glowup": "impressive transformation",
    "glow up": "impressive transformation",
    "glowed up": "transformed impressively",
    "era": "current phase of life",
    "in my era": "currently in a phase",
    "girl dinner": "minimal effortless meal",
    "girl math": "creative personal logic",
    "boy math": "male version of personal logic",
    "roman empire": "thing you think about often",
    "very demure": "very modest and reserved",
    "very mindful": "very thoughtful",
    "brat": "carefree rebellious attitude",
    "brat summer": "carefree summer attitude",
    "aura": "cool energy or vibe",
    "main character energy": "confident self centered energy",
    "vibe check": "assessing the mood",
    "passed the vibe check": "has good energy",
    "failed the vibe check": "has bad energy",
    "npc behavior": "acting robotic or predictable",
    "caught lacking": "caught off guard unprepared",
    "clout chasing": "seeking fame",
    "chronically online": "spending too much time online",
    "touch grass": "go outside and get fresh air",
    "based and redpilled": "admirable and aware",
    "cringe and bluepilled": "embarrassing and naive",
    "brain rot": "mind numbing content",
    "brainrot": "mind numbing content",
    "rent free": "always on your mind",
    "living in my head": "always on my mind",
    "this is fine": "sarcastic everything is bad",
    "we are so back": "things are good again",
    "it is so over": "things are hopeless",
    "he is so cooked": "he is in serious trouble",
    "cooked": "in serious trouble or done",
    "stick a fork in me": "i am done",
    "cooked": "finished or in trouble",
    "no shot": "no way that happened",
    "shot": "chance or attempt",
    "hard pass": "definitely no",
    "soft yes": "maybe or probably yes",
    "hard yes": "absolutely yes",
    "pass": "no thanks",


    
    # Greetings & Farewells
    "gm": "good morning",
    "gn": "good night",
    "gd": "good",
    "hru": "how are you",
    "hyd": "how are you doing",
    "wyd": "what are you doing",
    "wbu": "what about you",
    "wb": "welcome back",
    "tc": "take care",
    "ttyl": "talk to you later",
    "ttys": "talk to you soon",
    "cya": "see you",
    "cu": "see you",
    "bye": "goodbye",
    "bbye": "bye bye",

    # Common Abbreviations
    "u": "you",
    "r": "are",
    "ur": "your",
    "y": "why",
    "k": "okay",
    "kk": "okay okay",
    "ok": "okay",
    "ok": "okay",
    "ya": "yes",
    "yep": "yes",
    "yup": "yes",
    "nope": "no",
    "nah": "no",
    "na": "no",
    "m": "am",
    "i'm": "i am",
    "its": "it is",
    "thx": "thanks",
    "tx": "thanks",
    "ty": "thank you",
    "tq": "thank you",
    "yw": "you are welcome",
    "np": "no problem",
    "nw": "no worries",
    "pls": "please",
    "plz": "please",
    "plox": "please",
    "sry": "sorry",
    "srry": "sorry",
    "soz": "sorry",
    "mb": "my bad",
    "mybad": "my bad",
    "bc": "because",
    "bcz": "because",
    "bcoz": "because",
    "coz": "because",
    "cus": "because",
    "b4": "before",
    "b/c": "because",
    "w/": "with",
    "w/o": "without",
    "w8": "wait",
    "wt": "wait",
    "gr8": "great",
    "g8": "great",
    "l8": "late",
    "l8r": "later",
    "m8": "mate",
    "sk8": "skate",
    "h8": "hate",
    "str8": "straight",
    "2": "to",
    "2day": "today",
    "2moro": "tomorrow",
    "2mrw": "tomorrow",
    "2nite": "tonight",
    "4": "for",
    "4ever": "forever",
    "4get": "forget",
    "4ward": "forward",

    # Emotions & Reactions
    "lol": "laughing out loud",
    "lmao": "laughing my ass off",
    "lmfao": "laughing my freaking ass off",
    "rofl": "rolling on the floor laughing",
    "roflmao": "rolling on the floor laughing my ass off",
    "haha": "laughing",
    "hehe": "laughing softly",
    "omg": "oh my god",
    "omfg": "oh my freaking god",
    "omw": "oh my word",
    "wtf": "what the heck",
    "wth": "what the heck",
    "idgaf": "i don't give a care",
    "smh": "shaking my head",
    "fml": "this is frustrating",
    "ikr": "i know right",
    "ik": "i know",
    "ngl": "not gonna lie",
    "tbh": "to be honest",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "jk": "just kidding",
    "jkjk": "just kidding just kidding",
    "lmk": "let me know",
    "hmu": "hit me up",
    "ily": "i love you",
    "ily2": "i love you too",
    "ilysm": "i love you so much",
    "luv": "love",
    "lylas": "love you like a sister",
    "lylab": "love you like a brother",
    "xoxo": "hugs and kisses",
    "aww": "that is sweet",
    "awww": "that is sweet",
    "yay": "hooray",
    "woah": "wow",
    "woww": "wow",
    "meh": "i don't care",
    "bleh": "i feel bad",
    "ugh": "i am frustrated",
    "eww": "that is gross",
    "ew": "that is gross",
    "brr": "it is cold",

    # Texting Shortcuts
    "idk": "i don't know",
    "idc": "i don't care",
    "idk": "i don't know",
    "idfk": "i don't know",
    "nvm": "never mind",
    "nm": "never mind",
    "nvmd": "never mind",
    "brb": "be right back",
    "bbl": "be back later",
    "bbs": "be back soon",
    "afk": "away from keyboard",
    "irl": "in real life",
    "atm": "at the moment",
    "rn": "right now",
    "asap": "as soon as possible",
    "fyi": "for your information",
    "tbf": "to be fair",
    "imo": "in my opinion",
    "nbd": "no big deal",
    "nbd": "no big deal",
    "nt": "no thanks",
    "nty": "no thank you",
    "gtg": "got to go",
    "g2g": "got to go",
    "gotta": "got to",
    "gonna": "going to",
    "wanna": "want to",
    "kinda": "kind of",
    "sorta": "sort of",
    "hafta": "have to",
    "dunno": "don't know",
    "lemme": "let me",
    "gimme": "give me",
    "tryna": "trying to",
    "prolly": "probably",
    "probs": "probably",
    "prob": "probably",
    "def": "definitely",
    "deffo": "definitely",
    "defo": "definitely",
    "obv": "obviously",
    "obvs": "obviously",
    "abs": "absolutely",
    "tbqh": "to be quite honest",
    "imo": "in my opinion",
    "ftw": "for the win",
    "fwiw": "for what it is worth",
    "tmi": "too much information",
    "smth": "something",
    "sth": "something",
    "nthing": "nothing",
    "nth": "nothing",
    "evrythng": "everything",
    "evry": "every",
    "evn": "even",
    "thru": "through",
    "tho": "though",
    "altho": "although",
    "cmon": "come on",
    "c'mon": "come on",
    "dat": "that",
    "dis": "this",
    "dese": "these",
    "dem": "them",
    "der": "there",
    "dere": "there",
    "ders": "there is",
    "der's": "there is",
    "wot": "what",
    "wots": "what is",
    "wats": "what is",
    "wat": "what",
    "hw": "how",
    "hws": "how is",
    "wen": "when",
    "wer": "where",
    "wer's": "where is",
    "wit": "with",
    "nd": "and",
    "n": "and",
    "bt": "but",
    "bt": "but",
    "jst": "just",
    "jus": "just",
    "juz": "just",
    "abt": "about",
    "abt": "about",
    "alr": "already",
    "alrdy": "already",
    "rly": "really",
    "rlly": "really",
    "reli": "really",
    "vry": "very",
    "veri": "very",
    "v": "very",
    "dnt": "don't",
    "dont": "don't",
    "cant": "can't",
    "wont": "won't",
    "isnt": "isn't",
    "arent": "aren't",
    "didnt": "didn't",
    "doesnt": "doesn't",
    "havent": "haven't",
    "wasnt": "wasn't",
    "wouldnt": "wouldn't",
    "couldnt": "couldn't",
    "shouldnt": "shouldn't",

    # Social Media / Internet Slang
    "ootd": "outfit of the day",
    "tbt": "throwback thursday",
    "wcw": "woman crush wednesday",
    "mcm": "man crush monday",
    "dm": "direct message",
    "pm": "private message",
    "fb": "facebook",
    "ig": "instagram",
    "yt": "youtube",
    "wp": "whatsapp",
    "tw": "twitter",
    "rt": "retweet",
    "ff": "follow friday",
    "ama": "ask me anything",
    "tfw": "that feeling when",
    "mfw": "my face when",
    "mrw": "my reaction when",
    "iirc": "if i recall correctly",
    "afaik": "as far as i know",
    "eli5": "explain like i am five",
    "til": "today i learned",
    "oc": "original content",
    "op": "original poster",
    "ftfy": "fixed that for you",
    "iirc": "if i recall correctly",
    "yolo": "you only live once",
    "fomo": "fear of missing out",
    "goat": "greatest of all time",
    "lit": "exciting or amazing",
    "fire": "amazing",
    "slay": "doing great",
    "vibe": "feeling or mood",
    "lowkey": "secretly or quietly",
    "highkey": "openly or very much",
    "sus": "suspicious",
    "suss": "suspicious",
    "cap": "lie",
    "nocap": "no lie",
    "no cap": "no lie",
    "bussin": "really good",
    "snatched": "looking amazing",
    "extra": "over the top",
    "shade": "disrespect",
    "tea": "gossip",
    "bet": "okay or agreed",
    "periodt": "end of discussion",
    "period": "end of discussion",
    "sis": "sister",
    "bro": "brother",
    "bruh": "brother or expression of disbelief",
    "brah": "brother",
    "fam": "family or close friends",
    "squad": "close friend group",
    "crew": "close friend group",
    "bae": "before anyone else or loved one",
    "bff": "best friends forever",
    "bf": "boyfriend",
    "gf": "girlfriend",
    "bffl": "best friends for life",
    "sis": "sister",
    "bestie": "best friend",

    # Expressions
    "ikwym": "i know what you mean",
    "wywh": "wish you were here",
    "hand": "have a nice day",
    "hagd": "have a great day",
    "hags": "have a great summer",
    "hagn": "have a great night",
    "hhoj": "ha ha only joking",
    "iykyk": "if you know you know",
    "noyb": "none of your business",
    "myob": "mind your own business",
    "stfu": "please be quiet",
    "sthu": "please be quiet",
    "gtfo": "get out",
    "omfg": "oh my goodness",
    "omg": "oh my goodness",
    "yikes": "that is bad or scary",
    "oof": "that is unfortunate",
    "rip": "rest in peace",
    "lmk": "let me know",
    "wdym": "what do you mean",
    "wdyt": "what do you think",
    "wdus": "what do you suggest",
    "iirc": "if i recall correctly",
    "nsfw": "not safe for work",
    "nsfl": "not safe for life",





    










}

# ─────────────────────────────────────────
# USAGE FUNCTION
# ─────────────────────────────────────────
def replace_chat_words(text):
    """Replace chat words/slang in text using master dictionary."""
    pattern = re.compile(
        r'\b(' + '|'.join(re.escape(k) for k in master_chat_dict.keys()) + r')\b',
        re.IGNORECASE
    )
    return pattern.sub(lambda m: master_chat_dict[m.group(0).lower()], text)


def get_meaning(word):
    """Get the meaning of a single chat word."""
    return master_chat_dict.get(word.lower(), f"'{word}' not found in dictionary")


def search_dict(keyword):
    """Search dictionary for words containing keyword."""
    results = {k: v for k, v in master_chat_dict.items() if keyword.lower() in k.lower()}
    return results


# ─────────────────────────────────────────
# TESTING
# ─────────────────────────────────────────
if __name__ == "__main__":
    print(f"✅ Total chat words in dictionary: {len(master_chat_dict)}\n")

    tests = [
        "omg wyd rn brb lmao",
        "tbh u r gr8 ngl",
        "idk wbu hru atm",
        "gg wp ez game bro lfg",
        "no cap he got rizz and slay",
        "delulu is the solulu periodt bestie",
        "smh fml this is so mid bruh",
        "fr fr lowkey highkey bussin ngl",
        "ily bae ur literally my otp",
        "glhf everyone lets gg this match",
        "gonna wanna kinda sorta prolly deffo",
        "tysm for the deets on the tea sis",
        "he went off and ate that no cap",
        "the vibe check failed smh shook af",
        "caught him lacking in 4k deadass",
    ]

    print("─" * 60)
    for t in tests:
        print(f"INPUT : {t}")
        print(f"OUTPUT: {replace_chat_words(t)}")
        print("─" * 60)

    print("\n📖 Example: Get meaning of a word")
    for word in ["rizz", "bussin", "no cap", "slay", "lowkey", "gg", "brb", "tbh"]:
        print(f"  {word:15} → {get_meaning(word)}")
